# Generated by Django 2.1.7 on 2019-03-03 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('flow_method', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('flow_type', models.CharField(choices=[('0', 'Expense'), ('1', 'Income')], default='0', max_length=1)),
                ('slug', models.SlugField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_statements_reader.Budget')),
            ],
        ),
    ]
