# Generated by Django 2.1.7 on 2019-03-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements_reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
