# Generated by Django 2.1.7 on 2019-06-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statements_reader', '0007_auto_20190501_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Transportation', 'Transportation'), ('HealthCare', 'HealthCare'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Education', 'Education'), ('Supplies', 'Supplies')], default=None, max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BankStatementReader',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='bank_statements_reader.Category'),
        ),
    ]
